---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directories:
      - /modules/wif/
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
